### PR TITLE
Facebook feed to footer

### LINKED ISSUE #46: Implement Facebook feed
**Describe the feature you'd like**
As discussed with @harry-hov and the team, we'll need to implement the Facebook feed.

**Wireframe / Mockup / Rough drawing / Screenshot**  
It has to be on the right side of the footer

**Would you like to work on the issue?**
- [ ] Yes
- [x] No @harry-hov plans to work on this

**Before you post, make sure you have:**
- [ ] assigned yourself to the issue if you want to work on it
- [x] added the correct labels to the issue

### PR DESCRIPTION
**Pull request by harry-hov**
Signed-off-by: Hariom Verma <hariom18599@gmail.com>

Fixes #46 

**Checklist:**

- [x] I have squashed my commits
- [x] My PR follows the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream development/master branch.

Changes: Facebook Feed

**Screenshots for the change** (if applicable):

### CODE REVIEW

**Comment by harry-hov** [comment]
## Screenshot
Screenshot (107)

**Comment by mooocer** [comment]
The old squished partial circles one looked better. It should also be centered.

**Comment by harry-hov** [comment]
Ok, will modify this to old one

**Comment by harry-hov** [comment]
## Screenshot
Capture111

Ready for review @mishuvs

**Review by mooocer — APPROVED** [review]
Nice work @harry-hov :tada: :clap:

**Pull request merged**
