### PR TITLE
fix: implemented events section

### LINKED ISSUE #29: Revamp event section
**Describe the feature you'd like**
*The events section, which is currently in the header section as a slider will look better if it is given a separate section and the events are organized into cards. The upcoming events will be arranged as cards and past events as a slider below the card section*

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Before you post, make sure you have:**
- [ ] assigned yourself to the issue if you want to work on it
- [x] added the correct labels to the issue

### PR DESCRIPTION
**Pull request by indraasura**
Fixes #29 
**Checklist:**

- [x] I have squashed my commits
- [x] My PR follows the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream development/master branch.

Changes: 

Added separate events section to include cards of all conducted events

### CODE REVIEW

**Review by shashank-sharma — APPROVED** [review]

**Review by mooocer — CHANGES_REQUESTED** [review]
@indraasura Kindly make the changes as discussed, namely:
1. spacing
2. background-color

**Comment by indraasura** [comment]
> @indraasura Kindly make the changes as discussed, namely:
> 
> 1. spacing
> 2. background-color

okay sure

**Review by mooocer — CHANGES_REQUESTED** [review]
These are your commit messages: 
- "event cards scaled down and spaces removed"
- "background changed"

The commits should be squashed into one commit, and the commit message should be something like: "Add events section".

**Review by mooocer — APPROVED** [review]
Nice work @indraasura :tada: :clap:

**Pull request merged**
