### PR TITLE
Add grey background

### LINKED ISSUE #20: Navigation bar contents not visible
When the carousel gets a background with light colors, the links being white are not visible to eyes.
I would suggest adding a grey gradient to it. So that navigation bar gets independent of the background of the carousel.

### PR DESCRIPTION
**Pull request by geekayush**
Fixes #20 

Changes: Add gradient background and box-shadow to navbar to make the contents visible even on lighter backgrounds.

Screenshot from 2019-08-23 15-26-26

### CODE REVIEW

**Comment by mooocer** [comment]
Thanks for opening the pull request @geekayush! But, I was talking about [this type](https://user-images.githubusercontent.com/8490079/35911716-dfc8c024-0bfa-11e8-8389-2ecfcd49057b.png) of gradient. It will look better and give continuity to the site. Can you please change it to that instead?

**Comment by geekayush** [comment]
I have changed it to the one shown below
Screenshot from 2019-08-23 17-56-15
P.S. Setting a lesser opaque background on the 'navbar' would seem changing colors because of the carousel backgrounds.

**Comment by mooocer** [comment]
@geekayush But this looks completely opaque. 
We need it to be shadowed around the corners. With the distance from the top, visibility of the shadow should decrease.
Something like this blog: https://css-tricks.com/snippets/css/top-shadow/, similar shadow but larger height.

**Comment by mishuvs** [comment]
Really appreciate your contribution @geekayush but doesn't seem to align with goals :pray:

**Pull request closed without merging**
